// Serial commands: RPi → ESP32 Controller
export enum SerialCommand {
  SET_RED = 'SET_RED',
  SET_GREEN = 'SET_GREEN',
  ENABLE_BUTTON = 'ENABLE_BUTTON',
  DISABLE_BUTTON = 'DISABLE_BUTTON',
  START_FILL_500ML = 'START_FILL_500ML',
  STOP_FILL = 'STOP_FILL',
  RESET_ERROR = 'RESET_ERROR',
  GET_STATUS = 'GET_STATUS',
  TEST_RELAY = 'TEST_RELAY',
  SET_FILL_DURATION = 'SET_FILL_DURATION',
  GET_FILL_DURATION = 'GET_FILL_DURATION',
}

// Serial responses: Controller → RPi
export enum SerialResponse {
  BUTTON_PRESSED = 'BUTTON_PRESSED',
  BUTTON_ENABLED = 'BUTTON_ENABLED',
  BUTTON_DISABLED = 'BUTTON_DISABLED',
  FILL_STARTED = 'FILL_STARTED',
  FILL_DONE = 'FILL_DONE',
  FILL_VOLUME_500 = 'FILL_VOLUME:500',
  ERROR = 'ERROR',
  EMERGENCY_STOP = 'EMERGENCY_STOP',
}
